# SPDX-FileCopyrightText: 2026 SUSE LLC
# SPDX-FileContributor: Cédric Bosdonnat
#
# SPDX-License-Identifier: MIT

# Dedicated ServiceAccount for the OpenBao Issuer to use
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-issuer-sa
  namespace: {{ .Values.certManagerNamespace }}
  labels:
    app.kubernetes.io/part-of: uyuni
---
# Fix for "forbidden: User ... cannot create resource 'serviceaccounts/token'"
# Without this the ServiceAccount for uyuni-openbao-issuer wouldn't get its token.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-token-requester
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-token-requester-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-token-requester
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: {{ .Values.certManagerNamespace }}
